# The graph called <data:,last-update-message> (which contains Fedora's last update message) contains a notification about a resource which
# wasGeneratedBy an Activity (e.g. by someone clicking the "update" button in Fedora's UI, or uploading a file via curl, etc). 
# Fedora classifies the Activity as either a modification, creation, deletion, or move.
PREFIX prov: <http://www.w3.org/ns/prov#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX event: <http://fedora.info/definitions/v4/event#>
SELECT ?eventType 
WHERE {
	GRAPH <data:,last-update-message> {
		?updatedResourceURI prov:wasGeneratedBy / rdf:type ?eventType.
		FILTER(?eventType IN (event:ResourceModification, event:ResourceDeletion, event:ResourceCreation, event:ResourceRelocation))
	}
}
